---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazonfed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amazonfed
  template:
    metadata:
      labels:
        app: amazonfed
    spec:
      containers:
      - name: amazonfed
        image: chndra/amazonwebapp:654
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: amazonfed-service
spec:
  selector:
    app: amazonfed
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
